"""add_origin_destination_columns

Revision ID: c3449aa5cb5b
Revises: e50e441bfedf
Create Date: 2025-08-28 01:06:39.161529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3449aa5cb5b'
down_revision: Union[str, Sequence[str], None] = 'e50e441bfedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Tambahkan kolom sebagai nullable
    op.add_column('flight_prices', sa.Column('origin', sa.String(length=3), nullable=True))
    op.add_column('flight_prices', sa.Column('destination', sa.String(length=3), nullable=True))
    
    # Step 2: Update data berdasarkan airline code
    flight_prices_table = sa.table(
        'flight_prices',
        sa.column('flight_number', sa.String),
        sa.column('origin', sa.String),
        sa.column('destination', sa.String)
    )
    
    # Update berdasarkan airline code dalam flight_number
    airline_mapping = {
        'GA': ('CGK', 'DPS'),  # Garuda: Jakarta to Denpasar
        'SQ': ('SIN', 'CGK'),  # Singapore Airlines: Singapore to Jakarta
        'AK': ('KUL', 'CGK'),  # AirAsia: Kuala Lumpur to Jakarta
        'QG': ('CGK', 'SUB'),  # Citilink: Jakarta to Surabaya
        'SJ': ('CGK', 'DPS'),  # Sriwijaya: Jakarta to Denpasar
    }
    
    for airline_code, (origin, dest) in airline_mapping.items():
        op.execute(
            flight_prices_table.update()
            .where(flight_prices_table.c.flight_number.like(f'{airline_code}%'))
            .values(origin=origin, destination=dest)
        )
    
    # Step 3: Handle case untuk flight_number yang tidak match
    op.execute(
        flight_prices_table.update()
        .where(flight_prices_table.c.origin.is_(None))
        .values(origin='CGK', destination='DPS')  # Default value
    )
    
    # Step 4: Set sebagai NOT NULL
    op.alter_column('flight_prices', 'origin', nullable=False)
    op.alter_column('flight_prices', 'destination', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_prices', 'destination')
    op.drop_column('flight_prices', 'origin')
    # ### end Alembic commands ###