"""insert bulk data to flight price table

Revision ID: e50e441bfedf
Revises: 0d4018d1bbaf
Create Date: 2025-07-06 18:47:26.911981

"""
from datetime import datetime, timedelta, date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50e441bfedf'
down_revision: Union[str, Sequence[str], None] = '0d4018d1bbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    flight_prices = sa.table('flight_prices',
        sa.column('flight_number', sa.String),
        sa.column('class', sa.String),
        sa.column('base_price', sa.Numeric),
        sa.column('tax', sa.Numeric),
        sa.column('fee', sa.Numeric),
        sa.column('currency', sa.String),
        sa.column('valid_from', sa.Date),
        sa.column('valid_to', sa.Date)
    )

    op.bulk_insert(flight_prices,
        [
            {
                'flight_number': 'GA123',
                'class': 'economy',
                'base_price': 150.00,
                'tax': 25.00,
                'fee': 10.00,
                'currency': 'USD',
                'valid_from': date.today(),
                'valid_to': date.today() + timedelta(days=30)
            },
            {
                'flight_number': 'GA123',
                'class': 'business',
                'base_price': 350.00,
                'tax': 50.00,
                'fee': 15.00,
                'currency': 'USD',
                'valid_from': date.today(),
                'valid_to': date.today() + timedelta(days=30)
            },
            {
                'flight_number': 'SQ456',
                'class': 'economy',
                'base_price': 250.00,
                'tax': 35.00,
                'fee': 15.00,
                'currency': 'SGD',
                'valid_from': date.today(),
                'valid_to': date.today() + timedelta(days=30)
            },
            {
                'flight_number': 'SQ456',
                'class': 'first',
                'base_price': 800.00,
                'tax': 100.00,
                'fee': 30.00,
                'currency': 'SGD',
                'valid_from': date.today(),
                'valid_to': date.today() + timedelta(days=30)
            },
            {
                'flight_number': 'AK789',
                'class': 'economy',
                'base_price': 120.00,
                'tax': 20.00,
                'fee': 5.00,
                'currency': 'MYR',
                'valid_from': date.today(),
                'valid_to': date.today() + timedelta(days=30)
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM flight_prices")
    # ### end Alembic commands ###
